# Generated by Django 4.2.10 on 2024-03-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ImageField(default='images/avatar.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='images/avatar.png', null=True, upload_to=''),
        ),
    ]
