# Generated by Django 4.2.10 on 2024-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_phone_number_student_matric_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
