# Generated by Django 4.2.10 on 2024-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
