# Generated by Django 4.2.10 on 2024-05-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_student_account_no_student_bank_name_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
