# Generated by Django 4.2.10 on 2024-04-02 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0002_alter_recruitment_image_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
