# Generated by Django 4.2.10 on 2024-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_saved_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
