# Generated by Django 4.2.10 on 2024-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_application_created_recruitment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
