# Generated by Django 4.2.10 on 2024-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_notification_options_notification_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('matric_no', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('level', models.CharField(max_length=3, null=True)),
                ('entry_year', models.CharField(max_length=4, null=True)),
                ('account_no', models.CharField(max_length=10, null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('company_address', models.CharField(max_length=300, null=True)),
                ('company_email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
