# Generated by Django 4.2.10 on 2024-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_acceptanceform'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceform',
            name='letter',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
